### ISSUE TITLE
Enemy stopped doing damage

### ISSUE THREAD

**Issue by Zopex** [JumberlackCoding/SpacerBaser#13]
Enemy was attacking energy node but was doing no damage.

This happened after it destroyed the original first solar collector. Luckily I had a backup one so the game kept going.

![image](https://cloud.githubusercontent.com/assets/11637816/6908389/b9f3b03e-d70a-11e4-8361-922062e94438.png)

**Comment by Voidraizer** [comment]
I believe this was solved with a semi-recent movement rework for the enemies.  If this happens again, please recreate this issue again and I'll look into it
